import serviceBase from "../Services/serviceBase";
const productService = {
    addfavorite:() =>serviceBase.post("/tmdb/v1/favorite/"+localStorage.getItem("login")+"/"+localStorage.getItem("content")),
    getcategories:()=>serviceBase.get("/tmdb/tv/1/categories/"),
    homepagecat: () => serviceBase.get("/tmdb/v1/homePage/{user_id}"+"/"+localStorage.getItem("presentcat")),
    delfavorite:() =>serviceBase.delete("/tmdb/v1/favorite/"+localStorage.getItem("login")+"/"+localStorage.getItem("content")),
    addwatchlater:() =>serviceBase.post("/tmdb/v1/recentlyWatch/"+localStorage.getItem("login")+"/"+localStorage.getItem("content")),
    delwatchlater:() =>serviceBase.delete("/tmdb/v1/recentlyWatch/"+localStorage.getItem("login")+"/"+localStorage.getItem("content")),
    favorite: () => serviceBase.get("/tmdb/v1/favorite/"+localStorage.getItem("login")),
    watchlater: () => serviceBase.get("/tmdb/v1/recentlyWatch/"+localStorage.getItem("login")),
    categories: () => serviceBase.get("/tmdb/tv/1/categories"),
    homepage: () => serviceBase.get("/tmdb/v1/homePage/{user_id}"),
    category: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/{category}"),
    seasons: () => serviceBase.get("/tmdb/tv/1/seasons/{TVShow_Id)"),
    tvshows: () => serviceBase.get("/tmdb/tv/1/shows"),
    episodes: () => serviceBase.get("/tmdb/tv/1/episodes/{seasons_id}"),
    action: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Action"),
    adventure: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Adventure"),
    animation: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Animation"),
    comedy: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Comedy"),
    crime: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Crime"),
    documentary: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Documentary"),
    drama: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Drama"),
    family: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Family"),
    fantasy: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Fantasy"),
    history: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/History"),
    horror: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Horror"),
    music: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Music"),
    mystery: () => serviceBase.get("/tmdb/v1/homePage/{user_id}/Mystery"),

    tvaction: () => serviceBase.get("/tmdb/tv/1/shows/Action"),
    tvadventure: () => serviceBase.get("/tmdb/tv/1/shows/Adventure"),
    tvanimation: () => serviceBase.get("/tmdb/tv/1/shows/Animation"),
    tvcomedy: () => serviceBase.get("/tmdb/tv/1/shows/Comedy"),
    tvcrime: () => serviceBase.get("/tmdb/tv/1/shows/Crime"),
    tvdocumentary: () => serviceBase.get("/tmdb/tv/1/shows/Documentary"),
    tvdrama: () => serviceBase.get("/tmdb/tv/1/shows/Drama"),
    tvfamily: () => serviceBase.get("/tmdb/tv/1/shows/Family"),
    tvfantasy: () => serviceBase.get("/tmdb/tv/1/shows/Fantasy"),
    tvhistory: () => serviceBase.get("/tmdb/tv/1/shows/History"),
    tvhorror: () => serviceBase.get("/tmdb/tv/1/shows/Horror"),
    tvmusic: () => serviceBase.get("/tmdb/tv/1/shows/Music"),
    tvmystery: () => serviceBase.get("/tmdb/tv/1/shows/Mystery"),
    kidsSeries: () => serviceBase.get("/tmdb/tv/1/shows/Kids"),
};
export default productService;
